# Generated by Django 4.1 on 2022-08-22 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0004_alter_testmodel_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testmodel',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AddField(
            model_name='testmodel',
            name='detailed_name',
            field=models.CharField(default='null', editable=False, max_length=255),
        ),
    ]
